### PR TITLE
Feature gate `allocator_api`

### PR DESCRIPTION
**Pull request by agerasev**
Disable unstable feature `allocator_api` if crate feature `allocator` is disabled. This allows to use this crate with stable Rust.

### CODE REVIEW

**Comment by schteve** [comment]
This sounds like a great idea! I might be missing something because when I test it I can't get it to build with stable (1.66.0). I get the same error I would expect if I was trying to use a feature gate. Is this perhaps something I'm doing wrong?
```
> cargo +stable build --no-default-features
...
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> freertos-rust\src/lib.rs:1:44
  |
1 | #![cfg_attr(feature = "allocator", feature(allocator_api))]
  |                                            ^^^^^^^^^^^^^
```

**Comment by agerasev** [comment]
I think I got it. You are probably running this command in the repository root, in which case cargo builds all workspace members including `freertos-rust-examples` which enables all `freertos-rust` default features even with `--no-default-features`.
To build only `freertos-rust` crate you need to go to its own directory and then run cargo:
```bash
cd freertos-rust
cargo +stable build --no-default-features --features=sync,time,hooks,interrupt
```

**Comment by schteve** [comment]
Ah, right! Forgot about the workspace. Thanks. All works as expected for me now so I'll go ahead and merge.
